In [175]:
from gurobipy import *
import numpy as np
import math as mt

In [176]:
nb_var = 12
nb_cont = 7
n = 2
p = 12

In [177]:
# Matrice utilite
matrice_utilite = np.array (
                [
                        [-5, -10, -2, -4, -1, -4, -3, -1, -1, -3, -1, -1],
                        [-3, -4, -6, -2, -3, -6, -1, -2, -4, -5, -1, -1]
                ]
        )

print(matrice_utilite)


[[ -5 -10  -2  -4  -1  -4  -3  -1  -1  -3  -1  -1]
 [ -3  -4  -6  -2  -3  -6  -1  -2  -4  -5  -1  -1]]


In [179]:
# vecteur w
w = [2, 1]

# creer le vecteur w'
w_prime = [(w[k] - w[k+1]) for k in range(len(w)-1)]
w_prime.append(w[-1])
print(w_prime)

[1, 1]


In [180]:
## les variables rk
coef_rk = []
for k in range(n):
        for i in range(n):
                coef_rk.append([])
                for j in range(n):
                        coef_rk[-1].append(0)
                coef_rk[-1][k] = 1
coef_rk = np.array(coef_rk)
print(coef_rk)

[[1 0]
 [1 0]
 [0 1]
 [0 1]]


In [181]:
## les variables bik
coef_bik = -1 * np.identity(n**2)
print(coef_bik)

[[-1. -0. -0. -0.]
 [-0. -1. -0. -0.]
 [-0. -0. -1. -0.]
 [-0. -0. -0. -1.]]


In [182]:
## les variables x
coef_xi = []
for k in range(n**2):
        coef_xi.append([])
        for i in range(p):
                coef_xi[-1].append(-u[k%n][i])
coef_xi = np.array(coef_xi)
print(coef_xi)

[[ 5 10  2  4  1  4  3  1  1  3  1  1]
 [ 3  4  6  2  3  6  1  2  4  5  1  1]
 [ 5 10  2  4  1  4  3  1  1  3  1  1]
 [ 3  4  6  2  3  6  1  2  4  5  1  1]]


In [183]:
# contrainte de l'existence d'un chemin
existe_chemin = np.array([
                [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [-1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, -1, 0, -1, 0, 0, 1, 1, -1, 0, 0, 0],
                [0, 0, -1, 0, -1, 0, 0, 0, 1, 1, 0, 0],
                [0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 1],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1]
        ])

print(existe_chemin)

[[ 1  1  1  0  0  0  0  0  0  0  0  0]
 [-1  0  0  1  1  1  0  0  0  0  0  0]
 [ 0 -1  0 -1  0  0  1  1 -1  0  0  0]
 [ 0  0 -1  0 -1  0  0  0  1  1  0  0]
 [ 0  0  0  0  0 -1 -1  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 -1  0 -1  0  1]
 [ 0  0  0  0  0  0  0  0  0  0 -1 -1]]


In [184]:
# concatenation des matrices rk, bik, xk 
result_concat = np.concatenate(
        (coef_rk, np.concatenate((coef_bik, coef_xi),axis=1)),
        axis=1)
print(result_concat)

[[ 1.  0. -1. -0. -0. -0.  5. 10.  2.  4.  1.  4.  3.  1.  1.  3.  1.  1.]
 [ 1.  0. -0. -1. -0. -0.  3.  4.  6.  2.  3.  6.  1.  2.  4.  5.  1.  1.]
 [ 0.  1. -0. -0. -1. -0.  5. 10.  2.  4.  1.  4.  3.  1.  1.  3.  1.  1.]
 [ 0.  1. -0. -0. -0. -1.  3.  4.  6.  2.  3.  6.  1.  2.  4.  5.  1.  1.]]


In [193]:

# ajout de la contrainte sur l'existence d'un chemin
new_lines = []
for i in range(nb_cont):
        new_lines.append([])
        for j in range(6):
                new_lines[-1].append(0)
new_lines = np.concatenate((new_lines, existe_chemin), axis=1)
constrainte = np.vstack([result_concat, new_lines])
print(constrainte)

[[ 1.  0. -1. -0. -0. -0.  5. 10.  2.  4.  1.  4.  3.  1.  1.  3.  1.  1.]
 [ 1.  0. -0. -1. -0. -0.  3.  4.  6.  2.  3.  6.  1.  2.  4.  5.  1.  1.]
 [ 0.  1. -0. -0. -1. -0.  5. 10.  2.  4.  1.  4.  3.  1.  1.  3.  1.  1.]
 [ 0.  1. -0. -0. -0. -1.  3.  4.  6.  2.  3.  6.  1.  2.  4.  5.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  0.  0.  1.  1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1.]]


In [194]:
# second membres
second_membre_1 = [0 for i in range(4)]

second_membre_existence_chemin =[0 for i in range(nb_cont)]
second_membre_existence_chemin[0] = 1
second_membre_existence_chemin[-1] = -1

second_membre = second_membre_1 + second_membre_existence_chemin

print(second_membre)

[0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1]


In [186]:
## coefficient fonction objectif
c = [(i+1) * w_prime[i] for i in range(n)] # coef des r_k
# coef des b_ik
for i in range(n) :
    for j in range(n) :
        c.append(-1*w_prime[i])

c += [0 for i in range(p)] # ajout des coef de x
c = np.array(c)
print(c)

[ 1  2 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0]


In [187]:
# Creer les models de la fonction objectif
m = Model("Question 4.2")

In [188]:
vars = ['ab', 'ac', 'ad', 'bc', 'bd', 'be', 'ce', 'cf', 'dc', 'df', 'eg', 'fg']
assert len(vars) == 12

x = []
for i in range(n):
            x.append(m.addVar(vtype=GRB.CONTINUOUS, lb=0, name="r%d" % (i+1)))
for i in range (n):
    for j in range(n):
        x.append(m.addVar(vtype=GRB.CONTINUOUS, lb=0, name="b%d%d" % ((j+1,(i+1)))))

for node in vars:
    x.append(m.addVar(vtype=GRB.CONTINUOUS, lb=0, name="X_%s" % node))
    
# maj du modele pour integrer les nouvelles variables
m.update()
print(x)

[<gurobi.Var r1>, <gurobi.Var r2>, <gurobi.Var b11>, <gurobi.Var b21>, <gurobi.Var b12>, <gurobi.Var b22>, <gurobi.Var X_ab>, <gurobi.Var X_ac>, <gurobi.Var X_ad>, <gurobi.Var X_bc>, <gurobi.Var X_bd>, <gurobi.Var X_be>, <gurobi.Var X_ce>, <gurobi.Var X_cf>, <gurobi.Var X_dc>, <gurobi.Var X_df>, <gurobi.Var X_eg>, <gurobi.Var X_fg>]


In [189]:
# definition de l'objectif
obj = LinExpr();
obj =0
for j in range(nb_cont):
    obj += c[j] * x[j]

m.setObjective(obj,GRB.MINIMIZE)

In [190]:
# Definition des contraintes
# Definition des contraintes
for i in range(4):
    m.addConstr(quicksum(constrainte[i][j]*x[j] for j in colonnes) <= second_membre[i], "Contrainte%d" % i)
    
for i in range(4, 11):
        m.addConstr(quicksum(constrainte[i][j]*x[j] for j in colonnes) == second_membre[i], "Contrainte%d" % i)

In [191]:
# Resolution
m.optimize()


print("")                
print('Solution optimale:')
mvars = m.getVars()
names = m.getAttr('VarName', mvars)
values = m.getAttr('X', mvars)
result = dict(zip(names, values))
for key in result:
    print(key,'=',result[key])
print("")
print('Valeur de la fonction objectif :', m.objVal)

Gurobi Optimizer version 10.0.0 build v10.0.0rc2 (linux64)

CPU model: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 11 rows, 18 columns and 44 nonzeros
Model fingerprint: 0xc03c20a2
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [1e+00, 2e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 1 rows and 0 columns
Presolve time: 0.04s

Solved in 0 iterations and 0.05 seconds (0.00 work units)
Infeasible or unbounded model

Solution optimale:


GurobiError: Unable to retrieve attribute 'X'