In [33]:
from gurobipy import *
import numpy as np
import math as mt

In [34]:
# Poser le nombre des varialbles et des contraintes
nbcont=7
nbvar=12


In [35]:
# Matrice des contraintes

contraintes = [
        [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [-1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, -1, 0, -1, 0, 0, 1, 1, -1, 0, 0, 0],
        [0, 0, -1, 0, -1, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1],
]
contraintes=np.array(contraintes)
print(contraintes)

[[ 1  1  1  0  0  0  0  0  0  0  0  0]
 [-1  0  0  1  1  1  0  0  0  0  0  0]
 [ 0 -1  0 -1  0  0  1  1 -1  0  0  0]
 [ 0  0 -1  0 -1  0  0  0  1  1  0  0]
 [ 0  0  0  0  0 -1 -1  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 -1  0 -1  0  1]
 [ 0  0  0  0  0  0  0  0  0  0 -1 -1]]


In [36]:
# Second membre
S=[1]
S+=[0 for i in range(nbcont-2)]
S+=[-1]
print(S)

[1, 0, 0, 0, 0, 0, -1]


In [37]:
# Coefficients de la fonction objectif
coef=[3,4,6,2,3,6,1,2,4,5,1,1]
print(coef)

[3, 4, 6, 2, 3, 6, 1, 2, 4, 5, 1, 1]


In [38]:
# Creer les models de la fonction objectif
m = Model("Partie4 scenario2") 

In [39]:
vars = ['ab', 'ac', 'ad', 'bc', 'bd', 'be', 'ce', 'cf', 'dc', 'df', 'eg', 'fg']
x = []
for i in vars :
    x.append(m.addVar(vtype=GRB.CONTINUOUS, lb=0, name="X%s" % (i)))

m.update()
print(x)


[<gurobi.Var Xab>, <gurobi.Var Xac>, <gurobi.Var Xad>, <gurobi.Var Xbc>, <gurobi.Var Xbd>, <gurobi.Var Xbe>, <gurobi.Var Xce>, <gurobi.Var Xcf>, <gurobi.Var Xdc>, <gurobi.Var Xdf>, <gurobi.Var Xeg>, <gurobi.Var Xfg>]


In [40]:
# definition de l'objectif
obj = LinExpr();
obj =0
for j in range(nbvar):
    obj += coef[j] * x[j]

m.setObjective(obj,GRB.MINIMIZE)

In [41]:
# Definition des contraintes
lignes = range(nbcont)
colonnes = range(nbvar)

for i in lignes:
    m.addConstr(quicksum(contraintes[i][j]*x[j] for j in colonnes) == S[i], "Contrainte%d" % i)

In [42]:
# Resolution
m.optimize()


print("")                
print('Solution optimale:')
mvars = m.getVars()
names = m.getAttr('VarName', mvars)
values = m.getAttr('X', mvars)
result = dict(zip(names, values))
for key in result:
    print(key,'=',result[key])
print("")
print('Valeur de la fonction objectif :', m.objVal)

Gurobi Optimizer version 10.0.0 build v10.0.0rc2 (mac64[x86])

CPU model: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads

Optimize a model with 7 rows, 12 columns and 24 nonzeros
Model fingerprint: 0x201815b2
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 3 rows and 3 columns
Presolve time: 0.01s
Presolved: 4 rows, 9 columns, 18 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    5.0000000e+00   2.000000e+00   0.000000e+00      0s
       1    6.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.02 seconds (0.00 work units)
Optimal objective  6.000000000e+00

Solution optimale:
Xab = 0.0
Xac = 1.0
Xad = 0.0
Xbc = 0.0
Xbd = 0.0
Xbe = 0.0
Xce = 1.0
Xcf = 0.0
Xdc = 0.0
Xdf = 0.0
Xeg = 1.0
Xfg = 0.0

Valeur de la fonction objectif :